classes:
- service.linux.system.container
- system.openstack.common.cluster
- service.rabbitmq.server.single
parameters:
  _param:
    single_address: 127.0.0.1
    rabbitmq_cluster_role: slave
  linux:
    system:
      name: "$HOSTNAME"
  rabbitmq:
    cluster:
      enabled: true
      role: none
      master: none
      members:
        - host: "$RABBITMQ_SERVER_NODE01_SERVICE_HOST"
          name: rabbitmq-server-node01
        - host: "$RABBITMQ_SERVER_NODE02_SERVICE_HOST"
          name: rabbitmq-server-node02
        - host: "$RABBITMQ_SERVER_NODE03_SERVICE_HOST"
          name: rabbitmq-server-node03
      mode: disc
      name: openstack
    server:
      host:
        '/':
          enabled: true
          user: guest
          password: guest
          policies:
          - name: HA
            pattern: '^(?!amq\.).*'
            definition: '{"ha-mode": "all", "message-ttl": 120000}'
        '/openstack':
          enabled: true
          user: openstack
          password: ${_param:rabbitmq_openstack_password}
          policies:
          - name: HA
            pattern: '^(?!amq\.).*'
            definition: '{"ha-mode": "all", "message-ttl": 120000}'